version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msi
    environment:
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      AzureAd__ClientId: ${AzureAd__ClientId}
      AzureAd__TenantId: ${AzureAd__TenantId}
      CypressTestSecret: ${cypressKey}
      ASPNETCORE_URLS: "https://+:8443" # Enable HTTPS on port 8443
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "SuperSecretPassword" # Replace with your actual password or use a secret
    depends_on:
      - sql
    ports:
      - "7088:8443" # Expose HTTPS port 8443 on host port 7088
    volumes:
      - ./certs/aspnetapp.pfx:/https/aspnetapp.pfx:ro # Mount your dev certificate
    command: ["/bin/bash", "-c", "./docker-entrypoint.sh dotnet Dfe.ManageSchoolImprovement.Frontend.dll"]

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
